show_me_the_bool = true

[mqtt]
broker_url = "hurl"
broker_port = 8883
username = "user"
password = "password"

[logging]
version = 1
disable_existing_loggers = false

[logging.formatters]
[logging.formatters.colored]
"()" = "colorlog.ColoredFormatter"
format = '%(log_color)s%(asctime)s - %(name)s - %(levelname)s - %(message)s%(reset)s'
datefmt = '%Y-%m-%dT%H:%M:%S%z'
[logging.formatters.colored.log_colors]
DEBUG = 'cyan'
INFO = 'green'
WARNING = 'yellow'
ERROR = 'red'
CRITICAL = 'red,bg_white'

[logging.handlers]
[logging.handlers.console]
formatter = 'colored'
class = 'logging.StreamHandler'
stream = 'ext://sys.stdout'

[logging.loggers]
[logging.loggers.root]
handlers = ['console']
level = 'DEBUG'
